//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.Pago = new HashSet<Pago>();
        }
    
        public int IDCita { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Motivo { get; set; }
        public string Diagnostico { get; set; }
        public int IDMascota { get; set; }
        public int IDVeterinario { get; set; }
        public int IDTipoCita { get; set; }
        public int IDEstadoCita { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> IDUsuarioRegistro { get; set; }
        public Nullable<int> IDUsuarioModificacion { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> DuracionEstimada { get; set; }
    
        public virtual EstadoCita EstadoCita { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual TipoCita TipoCita { get; set; }
        public virtual Veterinario Veterinario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
