//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IDPago { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Monto { get; set; }
        public int IDCita { get; set; }
        public int IDMetodoPago { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
    }
}
